### PR TITLE
Perform a userspace reboot if available on Odyssey/Chimera/Taurine

### PR DESCRIPTION
**Pull request by elihwyma**
Based on the logic from libhooker, usually more reliable than standard ldrestart

### CODE REVIEW

**Comment by CRKatri** [comment]
I have a couple things I would like to be added
1. A flag to skip the userspace reboot and only perform the ldrestart, maybe `-f`
2. Add information about this change to `man/ldrestart.1`
3. When a userspace reboot fails print the formatted error message from `xpc_strerro()`

**Comment by CRKatri** [comment]
It was also brought to my attention that checking the return of `reboot3()` will not work as a gauge for whether userspace reboots work. For example, on versions of Odyssey before 1.3.0, `reboot3()` will work but `jailbreakd` will not persist, losing the jailbreak. This will also not work on Checkra1n, where a userspace reboot will appear to work fine but actually cause issues.

**Comment by CRKatri** [comment]
I have decided that ldrestart should not perform a userspace reboot. An ldrestart and a userspace reboot are different and combining them will cause confusion and was originally proposed so that Sileo won't have to handle it, which I believe to be a better idea.

**Comment by dlevi309** [comment]
Alternative proposal; supply a separate tool to perform a userspace reboot (maybe?) code as light as this seems to do the job, I wanted to get your input on the matter @CRKatri before creating a full PR. 

`rbuserspace`
```c
#import <dlfcn.h>
#include <xpc/xpc.h>

#define RB_USERSPACE 0x2000000000000000ULL

extern int reboot3(uint64_t arg);

int main() {
	int userspaceError = reboot3(RB_USERSPACE);
	if (userspaceError == 0)
		return 0;
}
```
I think that there’s just cause behind providing this as a separate tool, being that you can only invoke a userspace reboot through launchctl atm (on the command line, not including different implementations through apps or tweaks)

**Comment by CRKatri** [comment]
Is this really useful? `launchctl` is pretty much always available. In either case, the code should actually be

```c
#include <stdio.h>

#define RB_USERSPACE 0x2000000000000000ULL
extern int reboot3(uint64_t);
extern const char *xpc_strerror(int);

int main() {
	int err = reboot3(RB_USERSPACE);
	if (err != 0) {
		fprintf(stderr, "%s\n", xpc_strerror(err));
		return 1;
	}
}
```

**Pull request closed without merging**
